### ISSUE TITLE
ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by msya** [linkedin/Spyglass#10]
Thank you for releasing this awesome library. I found an issue in the library or setup. It could be recreated with the sample app by following these steps: 

1. Do an @ mention, the suggestions list will be shown.
2. Keep the list open and dump the view hierarchy in Android Device Monitor. 
3. The following exceptions occur: 

```
java.lang.ClassNotFoundException: com.linkedin.android.spyglass.mentions.MentionsEditable
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:309)
     at java.lang.Class.forName(Class.java:273)
     ...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.linkedin.android.spyglass.mentions.MentionsEditable" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:309)
      at java.lang.Class.forName(Class.java:273)
      at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
      at android.os.Parcel.readParcelable(Parcel.java:2245)
      at android.os.Parcel.readValue(Parcel.java:2152)
      at android.os.Parcel.readListInternal(Parcel.java:2526)
      at android.os.Parcel.readList(Parcel.java:1661)
      at android.view.accessibility.AccessibilityEvent.readAccessibilityRecordFromParcel(AccessibilityEvent.java:1110)
      at android.view.accessibility.AccessibilityEvent.initFromParcel(AccessibilityEvent.java:1072)
      at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1415)
      at android.view.accessibility.AccessibilityEvent$1.createFromParcel(AccessibilityEvent.java:1412)
      at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:68)
      at android.os.Binder.execTransact(Binder.java:446)
    Suppressed: java.lang.ClassNotFoundException: com.linkedin.android.spyglass.mentions.MentionsEditable
      at java.lang.Class.classForName(Native Method)
      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
      ... 15 more
```

**Comment by nhibner** [comment]
Thanks for reporting this issue. I'm glad to see that you're using and enjoying the library. I'll take a look into this issue. Any clues as to why this is happening?

**Comment by amboone** [comment]
I'm seeing this issue in my app as well. I'm not sure how it's happening though; I'm just seeing it in the crash reports.

**Comment by nhibner** [comment]
I did more digging and discovered that the accessibility system (which is used when taking a dump of the view hierarchy) loads parcelable data using the default system classloader, which does not know about our libraries classes. I think we can avoid the issue by sending a regular Editable in the accessibility event rather than our custom MentionsEditable. I'll have a fix up soon.
