### ISSUE TITLE
MentionsEditable- IndexOutOfBoundsException

### ISSUE THREAD

**Issue by manojguptav** [linkedin/Spyglass#102]
Getting IndexOutOfBoundsException in field and monkey test

Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:682)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:674)
       at com.linkedin.android.spyglass.mentions.MentionsEditable.setSpan(MentionsEditable.java:87)
       at android.text.Selection.setSelection(Selection.java:93)
       at android.text.Selection.setSelection(Selection.java:77)
       at android.text.method.ArrowKeyMovementMethod.onTouchEvent(ArrowKeyMovementMethod.java:291)
       at android.widget.TextView.onTouchEvent(TextView.java:10188)
       at com.linkedin.android.spyglass.ui.MentionsEditText.onTouchEvent(MentionsEditText.java:240)
       at android.view.View.dispatchTouchEvent(View.java:12631)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2764)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:970)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1928)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3475)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:923)
       at android.view.View.dispatchPointerEvent(View.java:12889)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5456)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5219)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4688)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4758)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4716)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4871)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4724)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4928)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4688)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4758)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4716)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4724)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4688)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7528)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7497)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7448)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7652)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:330)
       at android.os.Looper.loop(Looper.java:169)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

**Comment by nhibner** [comment]
Hard to tell what could cause this without more info, but I've added a check to prevent the crash at runtime for now: https://github.com/linkedin/Spyglass/commit/3b7aa6e2fe940c638776f6c8e8d28f7e716ecedf
