### ISSUE TITLE
Crash in MentionsEditText.java

### ISSUE THREAD

**Issue by shindeyy** [linkedin/Spyglass#128]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.text.TextWatcher.beforeTextChanged(java.lang.CharSequence, int, int, int)' on a null object reference
       at com.linkedin.android.spyglass.ui.MentionsEditText$MyWatcher.sendBeforeTextChanged(MentionsEditText.java:633)
       at com.linkedin.android.spyglass.ui.MentionsEditText$MyWatcher.beforeTextChanged(MentionsEditText.java:566)
       at android.widget.TextView.sendBeforeTextChanged(TextView.java:10902)
       at android.widget.TextView.access$1300(TextView.java:399)
       at android.widget.TextView$ChangeWatcher.beforeTextChanged(TextView.java:14191)
       at android.text.SpannableStringBuilder.sendBeforeTextChanged(SpannableStringBuilder.java:1258)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:537)
       at com.linkedin.android.spyglass.mentions.MentionsEditable.replace(MentionsEditable.java:105)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:944)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:219)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:204)
       at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:192)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:572)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:134)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by nhibner** [comment]
Huh, interesting. I would not expect this crash to happen since that list should only contain non-null `TextWatcher` instances. However, we can add some additional null checks to code more defensively, which I've done [here](https://github.com/linkedin/Spyglass/commit/7b1c0934d02ffb4c25013efa9da5e0d8f339b0d4). Since this is the first report of this though, I am not planning on making a new release just for this.

**Comment by the-kool-sk** [comment]
I am also getting this repressively on our production app. Please can you make a release for this fix?

**Comment by nhibner** [comment]
@shindeyy @the-kool-sk done, use version 3.0.2, thanks

**Comment by the-kool-sk** [comment]
thank you so much @nhibner
