### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.

### ISSUE THREAD

**Issue by anthony3444** [linkedin/Spyglass#56]
Hi guys!

First at all, thank you very much for your awesome library!

An user of my App, had a strange crash yesterday on Samsung SM-G950F (Android 7.0). It's the first time. I never seen this crash before.

Do you have some explanations?

Thank you very much

```
Fatal Exception: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
       at android.view.InputChannel.nativeReadFromParcel(InputChannel.java)
       at android.view.InputChannel.readFromParcel(InputChannel.java:148)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:37)
       at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:111)
       at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus(IInputMethodManager.java:840)
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1765)
       at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1588)
       at com.linkedin.android.spyglass.ui.MentionsEditText.restartInput(MentionsEditText.java:1089)
       at com.linkedin.android.spyglass.ui.MentionsEditText.ensureMentionSpanIntegrity(MentionsEditText.java:835)
       at com.linkedin.android.spyglass.ui.MentionsEditText.access$1100(MentionsEditText.java:80)
       at com.linkedin.android.spyglass.ui.MentionsEditText$MyWatcher.afterTextChanged(MentionsEditText.java:612)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9506)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12455)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
       at com.linkedin.android.spyglass.mentions.MentionsEditable.replace(MentionsEditable.java:105)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
       at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:349)
       at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:68)
       at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:458)
       at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:357)
       at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
       at android.widget.TextView.doKeyDown(TextView.java:7407)
       at android.widget.TextView.onKeyDown(TextView.java:7190)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3337)
       at android.view.View.dispatchKeyEvent(View.java:10615)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1697)
       at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:599)
       at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1880)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3164)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:476)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5048)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5010)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4188)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by nhibner** [comment]
I've not seen this crash before. Can you reproduce it consistently?

**Comment by nhibner** [comment]
Closed due to lack of steps to reproduce the issue.
