### ISSUE TITLE
When copying text, no text is inserted

### ISSUE THREAD

**Issue by Tduty** [linkedin/Spyglass#75]
When copying text, text is not always inserted. It is possible to call super () in the "onTextContextMenuItem" method.

**Comment by Tduty** [comment]
An error occurs in this block of code.
`@NonNull
    @Override
    public SpannableStringBuilder replace(int start, int end, CharSequence tb, int tbstart, int tbend) {
        // On certain software keyboards, the editor appears to append a word minus the last character when it is really
        // trying to just delete the last character. Until we can figure out the root cause of this issue, the following
        // code remaps this situation to do a proper delete.
        if (start == end && start - tbend - 1 >= 0 && tb.length() > 1) {
            String insertString = tb.subSequence(tbstart, tbend).toString();
            String previousString = subSequence(start - tbend - 1, start - 1).toString();
            if (insertString.equals(previousString)) {
                // Delete a character
                return super.replace(start - 1, start, "", 0, 0);
            }
        }

        return super.replace(start, end, tb, tbstart, tbend);
    }
`
When we immediately after copying paste the same text. Even in the comments it’s not very clear why a block of code was added with the condition (if)

**Comment by 02gaurav** [comment]
I encountered the same error today. I have some text with mention  in my editbox when i copy it and insert it , my app got crashed . I am attaching the stack trace 

`Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
       at android.os.Parcel.readParcelableCreator(Parcel.java:2941)
       at android.os.Parcel.readParcelable(Parcel.java:2867)
       at android.os.Parcel.readParcelableArray(Parcel.java:2975)
       at android.os.Parcel.readValue(Parcel.java:2824)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3139)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
       at android.os.BaseBundle.unparcel(BaseBundle.java:226)
       at android.os.BaseBundle.getIntArray(BaseBundle.java:1374)
       at com.linkedin.android.spyglass.ui.MentionsEditText.pasteHoneycombImpl(MentionsEditText.java:382)
       at com.linkedin.android.spyglass.ui.MentionsEditText.paste(MentionsEditText.java:334)
       at com.linkedin.android.spyglass.ui.MentionsEditText.onTextContextMenuItem(MentionsEditText.java:295)`
